-- =====================================================
-- HISTORIAL DE CAMBIOS - DOA
-- Tabla técnica de auditoría. No reemplaza ninguna de
-- las 4 tablas de negocio existentes.
-- Registra automáticamente INSERT / UPDATE / DELETE.
-- =====================================================

create table if not exists public.historial_cambios (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  usuario_auth_id uuid,
  usuario_correo text,
  entidad text not null,
  registro_id text,
  tipo_cambio text not null,
  informacion_anterior jsonb,
  informacion_nueva jsonb
);

alter table public.historial_cambios enable row level security;

-- Solo administradores pueden consultar el historial.
drop policy if exists "Administradores pueden consultar historial" on public.historial_cambios;
create policy "Administradores pueden consultar historial"
on public.historial_cambios
for select
to authenticated
using (public.is_doa_admin());

-- No se habilita INSERT/UPDATE/DELETE directo para usuarios.
-- Los registros los crea exclusivamente el trigger de auditoría.


create or replace function public.registrar_historial_doa()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.historial_cambios (
    usuario_auth_id,
    usuario_correo,
    entidad,
    registro_id,
    tipo_cambio,
    informacion_anterior,
    informacion_nueva
  )
  values (
    auth.uid(),
    coalesce(auth.jwt()->>'email', 'Sin correo / proceso automático'),
    TG_TABLE_NAME,
    case
      when TG_OP = 'DELETE' then (OLD.id)::text
      else (NEW.id)::text
    end,
    TG_OP,
    case when TG_OP in ('UPDATE','DELETE') then to_jsonb(OLD) else null end,
    case when TG_OP in ('INSERT','UPDATE') then to_jsonb(NEW) else null end
  );
  return coalesce(NEW, OLD);
end;
$$;

-- Recrear triggers para evitar duplicados si se vuelve a ejecutar el script.
drop trigger if exists trg_historial_usuarios on public.usuarios;
drop trigger if exists trg_historial_perfiles on public.perfiles;
drop trigger if exists trg_historial_estandares_doa on public.estandares_doa;
drop trigger if exists trg_historial_cumplimiento on public.cumplimiento;

create trigger trg_historial_usuarios
after insert or update or delete on public.usuarios
for each row execute function public.registrar_historial_doa();

create trigger trg_historial_perfiles
after insert or update or delete on public.perfiles
for each row execute function public.registrar_historial_doa();

create trigger trg_historial_estandares_doa
after insert or update or delete on public.estandares_doa
for each row execute function public.registrar_historial_doa();

create trigger trg_historial_cumplimiento
after insert or update or delete on public.cumplimiento
for each row execute function public.registrar_historial_doa();

-- Verificación rápida después de ejecutar:
-- select * from public.historial_cambios order by created_at desc limit 20;
